# Generated by Django 4.2.7 on 2023-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.SmallIntegerField(default=0),
        ),
    ]
